import { CityData } from '@/types';

export const teluguCitiesData: CityData[] = [
  // Rajahmundry - Default City
  {
    city: {
      id: 'rajahmundry',
      name: 'Rajahmundry',
      state: 'Andhra Pradesh',
      description: 'Cultural capital of Andhra Pradesh on the banks of sacred Godavari',
      image: '/placeholder.svg',
      coordinates: { lat: 17.0005, lng: 81.8040 },
      popularPlacesCount: 15,
    },
    places: [
      {
        id: 'r1',
        name: 'Sri Veerabhadra Swamy Temple',
        category: 'Temple',
        description: 'Ancient temple dedicated to Lord Veerabhadra with magnificent architecture and spiritual significance',
        location: { lat: 17.0015, lng: 81.8050 },
        distance: 2.5,
        rating: 4.7,
        timings: '6:00 AM - 12:00 PM, 4:00 PM - 9:00 PM',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Rajahmundry',
        state: 'Andhra Pradesh',
        festivalInfo: [
          {
            id: 'f1',
            name: 'Maha Shivaratri',
            date: '2025-02-26',
            description: 'Grand celebration with special poojas and cultural programs',
            images: ['/placeholder.svg'],
            isPast: false,
          },
        ],
      },
      {
        id: 'r2',
        name: 'ISKCON Temple',
        category: 'Temple',
        description: 'Beautiful Krishna temple with serene atmosphere and daily aartis',
        location: { lat: 17.0025, lng: 81.8060 },
        distance: 3.0,
        rating: 4.8,
        timings: '4:30 AM - 1:00 PM, 4:00 PM - 9:00 PM',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Rajahmundry',
        state: 'Andhra Pradesh',
      },
      {
        id: 'r3',
        name: 'Godavari Pushkar Ghat',
        category: 'Tourist Spot',
        description: 'Sacred bathing ghat on Godavari river, famous for Pushkaralu celebrations',
        location: { lat: 16.9985, lng: 81.7990 },
        distance: 1.5,
        rating: 4.6,
        timings: 'Open 24 hours',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Rajahmundry',
        state: 'Andhra Pradesh',
      },
      {
        id: 'r4',
        name: 'Godavari Bridge',
        category: 'Monument',
        description: 'Iconic railway bridge connecting Rajahmundry with Kovvur, engineering marvel',
        location: { lat: 16.9950, lng: 81.7850 },
        distance: 4.0,
        rating: 4.5,
        timings: 'Visible all day',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Rajahmundry',
        state: 'Andhra Pradesh',
      },
      {
        id: 'r5',
        name: 'Papi Hills',
        category: 'Tourist Spot',
        description: 'Scenic hill station with boat rides through Godavari gorge',
        location: { lat: 17.2830, lng: 81.2660 },
        distance: 45.0,
        rating: 4.9,
        timings: '6:00 AM - 6:00 PM',
        entryFee: 'Boat charges apply',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Rajahmundry',
        state: 'Andhra Pradesh',
      },
      {
        id: 'r6',
        name: 'Kadiyapulanka',
        category: 'Park',
        description: 'Beautiful riverside park perfect for evening walks and family outings',
        location: { lat: 17.0100, lng: 81.8100 },
        distance: 2.0,
        rating: 4.3,
        timings: '5:00 AM - 9:00 PM',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Rajahmundry',
        state: 'Andhra Pradesh',
      },
      {
        id: 'r7',
        name: 'Dowleswaram Barrage',
        category: 'Monument',
        description: 'Historic irrigation structure built by Sir Arthur Cotton on Godavari',
        location: { lat: 16.9800, lng: 81.8200 },
        distance: 5.5,
        rating: 4.4,
        timings: '6:00 AM - 6:00 PM',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Rajahmundry',
        state: 'Andhra Pradesh',
      },
      {
        id: 'r8',
        name: 'Sri Markandeya Temple',
        category: 'Temple',
        description: 'Ancient Shiva temple with historical significance and peaceful ambiance',
        location: { lat: 17.0050, lng: 81.8100 },
        distance: 3.5,
        rating: 4.6,
        timings: '6:00 AM - 8:00 PM',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Rajahmundry',
        state: 'Andhra Pradesh',
      },
    ],
    utsavs: [
      {
        id: 'u1',
        name: 'Godavari Pushkaralu',
        date: '2027-07-15',
        description: 'Sacred bathing festival that occurs once in 12 years when Jupiter enters Leo zodiac',
        images: ['/placeholder.svg'],
        isPast: false,
        city: 'Rajahmundry',
        category: 'Religious',
      },
      {
        id: 'u2',
        name: 'Karthika Masam',
        date: '2024-11-15',
        description: 'Month-long celebration with daily Godavari Harathi and cultural programs',
        images: ['/placeholder.svg'],
        isPast: false,
        city: 'Rajahmundry',
        category: 'Religious',
      },
    ],
    buses: [
      {
        id: 'b1',
        number: '365',
        name: 'Rajahmundry - Vijayawada Express',
        type: 'Express',
        departureTime: '6:00 AM',
        arrivalTime: '10:00 AM',
        fare: 250,
        route: 'Rajahmundry Bus Stand - Kovvur - Eluru - Vijayawada',
      },
      {
        id: 'b2',
        number: '720',
        name: 'Rajahmundry - Visakhapatnam Garuda',
        type: 'Garuda',
        departureTime: '7:30 AM',
        arrivalTime: '11:30 AM',
        fare: 350,
        route: 'Rajahmundry - Tuni - Anakapalli - Visakhapatnam',
      },
    ],
  },

  // Vijayawada
  {
    city: {
      id: 'vijayawada',
      name: 'Vijayawada',
      state: 'Andhra Pradesh',
      description: 'Major city on Krishna river, known for Kanaka Durga Temple',
      image: '/placeholder.svg',
      coordinates: { lat: 16.5062, lng: 80.6480 },
      popularPlacesCount: 12,
    },
    places: [
      {
        id: 'v1',
        name: 'Kanaka Durga Temple',
        category: 'Temple',
        description: 'Famous hilltop temple dedicated to Goddess Durga, major pilgrimage site',
        location: { lat: 16.5167, lng: 80.6211 },
        distance: 2.0,
        rating: 4.9,
        timings: '4:00 AM - 12:30 PM, 3:00 PM - 9:30 PM',
        entryFee: 'Free (Special darshan tickets available)',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Vijayawada',
        state: 'Andhra Pradesh',
        festivalInfo: [
          {
            id: 'vf1',
            name: 'Dasara Navaratri',
            date: '2024-10-12',
            description: '9-day grand celebration with special poojas and cultural events',
            images: ['/placeholder.svg'],
            isPast: false,
          },
        ],
      },
      {
        id: 'v2',
        name: 'Prakasam Barrage',
        category: 'Monument',
        description: 'Iconic bridge across Krishna river connecting Vijayawada with Guntur district',
        location: { lat: 16.5205, lng: 80.6186 },
        distance: 3.0,
        rating: 4.5,
        timings: 'Open 24 hours',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Vijayawada',
        state: 'Andhra Pradesh',
      },
      {
        id: 'v3',
        name: 'Bhavani Island',
        category: 'Park',
        description: 'Largest river island in India on Krishna river with water sports',
        location: { lat: 16.5400, lng: 80.6300 },
        distance: 5.0,
        rating: 4.6,
        timings: '10:00 AM - 6:00 PM',
        entryFee: '₹50 per person',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Vijayawada',
        state: 'Andhra Pradesh',
      },
      {
        id: 'v4',
        name: 'Undavalli Caves',
        category: 'Monument',
        description: 'Ancient rock-cut caves with Buddhist and Hindu sculptures',
        location: { lat: 16.5183, lng: 80.5792 },
        distance: 8.0,
        rating: 4.7,
        timings: '9:00 AM - 6:00 PM',
        entryFee: '₹25 per person',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Vijayawada',
        state: 'Andhra Pradesh',
      },
      {
        id: 'v5',
        name: 'Mangalagiri Temple',
        category: 'Temple',
        description: 'Ancient Narasimha Swamy temple on hill with unique Panakam offering tradition',
        location: { lat: 16.4308, lng: 80.5675 },
        distance: 12.0,
        rating: 4.8,
        timings: '6:00 AM - 8:00 PM',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Vijayawada',
        state: 'Andhra Pradesh',
      },
    ],
    utsavs: [
      {
        id: 'vu1',
        name: 'Krishna Pushkaralu',
        date: '2027-08-01',
        description: 'Sacred bathing festival in Krishna river once every 12 years',
        images: ['/placeholder.svg'],
        isPast: false,
        city: 'Vijayawada',
        category: 'Religious',
      },
    ],
    buses: [
      {
        id: 'vb1',
        number: '365',
        name: 'Vijayawada - Rajahmundry Express',
        type: 'Express',
        departureTime: '6:30 AM',
        arrivalTime: '10:30 AM',
        fare: 250,
        route: 'Vijayawada - Eluru - Kovvur - Rajahmundry',
      },
    ],
  },

  // Tirupati
  {
    city: {
      id: 'tirupati',
      name: 'Tirupati',
      state: 'Andhra Pradesh',
      description: 'World-famous pilgrimage city, home to Sri Venkateswara Temple',
      image: '/placeholder.svg',
      coordinates: { lat: 13.6288, lng: 79.4192 },
      popularPlacesCount: 10,
    },
    places: [
      {
        id: 't1',
        name: 'Tirumala Venkateswara Temple',
        category: 'Temple',
        description: 'World\'s richest temple dedicated to Lord Venkateswara, visited by millions',
        location: { lat: 13.6833, lng: 79.3472 },
        distance: 22.0,
        rating: 5.0,
        timings: '2:30 AM - 1:00 AM (next day)',
        entryFee: 'Free (Special darshan tickets available)',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Tirupati',
        state: 'Andhra Pradesh',
        festivalInfo: [
          {
            id: 'tf1',
            name: 'Brahmotsavam',
            date: '2024-10-04',
            description: 'Nine-day annual festival with grand processions and rituals',
            images: ['/placeholder.svg'],
            isPast: false,
          },
          {
            id: 'tf2',
            name: 'Vaikunta Ekadasi',
            date: '2025-01-10',
            description: 'Most auspicious day when Vaikunta Dwaram opens',
            images: ['/placeholder.svg'],
            isPast: false,
          },
        ],
      },
      {
        id: 't2',
        name: 'Sri Govindaraja Swamy Temple',
        category: 'Temple',
        description: 'Ancient Vishnu temple in Tirupati town with beautiful architecture',
        location: { lat: 13.6352, lng: 79.4192 },
        distance: 1.0,
        rating: 4.7,
        timings: '6:00 AM - 9:00 PM',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Tirupati',
        state: 'Andhra Pradesh',
      },
      {
        id: 't3',
        name: 'Kapila Theertham',
        category: 'Tourist Spot',
        description: 'Waterfall and Shiva temple at foot of Tirumala hills',
        location: { lat: 13.6458, lng: 79.3667 },
        distance: 5.0,
        rating: 4.5,
        timings: '6:00 AM - 6:00 PM',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Tirupati',
        state: 'Andhra Pradesh',
      },
      {
        id: 't4',
        name: 'Chandragiri Fort',
        category: 'Monument',
        description: 'Historic fort with palace and museum showcasing Vijayanagara architecture',
        location: { lat: 13.5833, lng: 79.3167 },
        distance: 15.0,
        rating: 4.4,
        timings: '9:00 AM - 5:00 PM',
        entryFee: '₹50 per person',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Tirupati',
        state: 'Andhra Pradesh',
      },
    ],
    utsavs: [
      {
        id: 'tu1',
        name: 'Annual Brahmotsavam',
        date: '2024-10-04',
        description: 'Grandest festival with Garuda Seva and Rathotsavam',
        images: ['/placeholder.svg'],
        isPast: false,
        city: 'Tirupati',
        category: 'Religious',
      },
    ],
    buses: [
      {
        id: 'tb1',
        number: '900',
        name: 'Tirupati - Tirumala Ghat Road',
        type: 'AC',
        departureTime: '5:00 AM',
        arrivalTime: '6:00 AM',
        fare: 50,
        route: 'Tirupati - Alipiri - Tirumala',
      },
    ],
  },

  // Visakhapatnam
  {
    city: {
      id: 'visakhapatnam',
      name: 'Visakhapatnam',
      state: 'Andhra Pradesh',
      description: 'Port city on Bay of Bengal, known for beaches and temples',
      image: '/placeholder.svg',
      coordinates: { lat: 17.6868, lng: 83.2185 },
      popularPlacesCount: 14,
    },
    places: [
      {
        id: 'vs1',
        name: 'Simhachalam Temple',
        category: 'Temple',
        description: 'Ancient Varaha Narasimha temple on hill with unique deity form',
        location: { lat: 17.7625, lng: 83.2542 },
        distance: 16.0,
        rating: 4.8,
        timings: '4:00 AM - 9:00 PM',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Visakhapatnam',
        state: 'Andhra Pradesh',
        festivalInfo: [
          {
            id: 'vsf1',
            name: 'Chandanotsavam',
            date: '2025-05-15',
            description: '13-day festival when Lord is anointed with sandalwood paste',
            images: ['/placeholder.svg'],
            isPast: false,
          },
        ],
      },
      {
        id: 'vs2',
        name: 'RK Beach',
        category: 'Tourist Spot',
        description: 'Popular beach with submarine museum and beautiful sunset views',
        location: { lat: 17.7231, lng: 83.3253 },
        distance: 3.0,
        rating: 4.6,
        timings: 'Open 24 hours',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Visakhapatnam',
        state: 'Andhra Pradesh',
      },
      {
        id: 'vs3',
        name: 'Kailasagiri',
        category: 'Park',
        description: 'Hilltop park with panoramic city views and giant Shiva-Parvati statue',
        location: { lat: 17.7364, lng: 83.3214 },
        distance: 5.0,
        rating: 4.7,
        timings: '8:00 AM - 8:00 PM',
        entryFee: '₹40 per person',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Visakhapatnam',
        state: 'Andhra Pradesh',
      },
      {
        id: 'vs4',
        name: 'Borra Caves',
        category: 'Monument',
        description: 'Million-year-old limestone caves in Araku valley with stalactites',
        location: { lat: 18.2833, lng: 83.0500 },
        distance: 90.0,
        rating: 4.8,
        timings: '10:00 AM - 5:30 PM',
        entryFee: '₹90 per person',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Visakhapatnam',
        state: 'Andhra Pradesh',
      },
      {
        id: 'vs5',
        name: 'Araku Valley',
        category: 'Tourist Spot',
        description: 'Scenic hill station with coffee plantations and tribal museum',
        location: { lat: 18.3273, lng: 82.8756 },
        distance: 115.0,
        rating: 4.9,
        timings: 'Open all day',
        entryFee: 'Free (Museum charges apply)',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Visakhapatnam',
        state: 'Andhra Pradesh',
      },
    ],
    utsavs: [
      {
        id: 'vsu1',
        name: 'Visakha Utsav',
        date: '2025-01-18',
        description: 'Annual cultural festival showcasing Andhra traditions',
        images: ['/placeholder.svg'],
        isPast: false,
        city: 'Visakhapatnam',
        category: 'Cultural',
      },
    ],
    buses: [
      {
        id: 'vsb1',
        number: '720',
        name: 'Visakhapatnam - Rajahmundry Garuda',
        type: 'Garuda',
        departureTime: '7:00 AM',
        arrivalTime: '11:00 AM',
        fare: 350,
        route: 'Visakhapatnam - Anakapalli - Tuni - Rajahmundry',
      },
    ],
  },

  // Hyderabad
  {
    city: {
      id: 'hyderabad',
      name: 'Hyderabad',
      state: 'Telangana',
      description: 'Capital city known for Charminar, biryani, and rich heritage',
      image: '/placeholder.svg',
      coordinates: { lat: 17.3850, lng: 78.4867 },
      popularPlacesCount: 18,
    },
    places: [
      {
        id: 'h1',
        name: 'Birla Mandir',
        category: 'Temple',
        description: 'White marble temple dedicated to Lord Venkateswara on hilltop',
        location: { lat: 17.4065, lng: 78.4691 },
        distance: 3.0,
        rating: 4.7,
        timings: '7:00 AM - 12:00 PM, 3:00 PM - 9:00 PM',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Hyderabad',
        state: 'Telangana',
      },
      {
        id: 'h2',
        name: 'Charminar',
        category: 'Monument',
        description: 'Iconic 400-year-old monument and mosque, symbol of Hyderabad',
        location: { lat: 17.3616, lng: 78.4747 },
        distance: 5.0,
        rating: 4.6,
        timings: '9:30 AM - 5:30 PM',
        entryFee: '₹25 per person',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Hyderabad',
        state: 'Telangana',
      },
      {
        id: 'h3',
        name: 'Hussain Sagar Lake',
        category: 'Tourist Spot',
        description: 'Large artificial lake with Buddha statue in center',
        location: { lat: 17.4239, lng: 78.4738 },
        distance: 2.0,
        rating: 4.5,
        timings: 'Open 24 hours',
        entryFee: 'Free (Boat rides charged)',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Hyderabad',
        state: 'Telangana',
      },
      {
        id: 'h4',
        name: 'Ramoji Film City',
        category: 'Park',
        description: 'World\'s largest film city with sets and entertainment shows',
        location: { lat: 17.2544, lng: 78.6808 },
        distance: 30.0,
        rating: 4.8,
        timings: '9:00 AM - 7:30 PM',
        entryFee: '₹1,150 onwards',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Hyderabad',
        state: 'Telangana',
      },
      {
        id: 'h5',
        name: 'Salar Jung Museum',
        category: 'Museum',
        description: 'One of India\'s largest museums with art and antique collections',
        location: { lat: 17.3713, lng: 78.4804 },
        distance: 4.0,
        rating: 4.7,
        timings: '10:00 AM - 5:00 PM (Closed on Friday)',
        entryFee: '₹50 per person',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Hyderabad',
        state: 'Telangana',
      },
      {
        id: 'h6',
        name: 'Chilkur Balaji Temple',
        category: 'Temple',
        description: 'Visa Balaji temple where devotees pray for visa success',
        location: { lat: 17.3667, lng: 78.3333 },
        distance: 25.0,
        rating: 4.8,
        timings: '6:00 AM - 7:00 PM',
        entryFee: 'Free',
        image: '/placeholder.svg',
        thumbnail: '/placeholder.svg',
        city: 'Hyderabad',
        state: 'Telangana',
      },
    ],
    utsavs: [
      {
        id: 'hu1',
        name: 'Bonalu',
        date: '2025-07-20',
        description: 'Traditional Telangana festival honoring Goddess Mahakali',
        images: ['/placeholder.svg'],
        isPast: false,
        city: 'Hyderabad',
        category: 'Traditional',
      },
      {
        id: 'hu2',
        name: 'Bathukamma',
        date: '2024-10-10',
        description: 'Floral festival celebrated by Telangana women',
        images: ['/placeholder.svg'],
        isPast: false,
        city: 'Hyderabad',
        category: 'Traditional',
      },
    ],
    buses: [
      {
        id: 'hb1',
        number: '555',
        name: 'Hyderabad - Vijayawada AC',
        type: 'AC',
        departureTime: '10:00 PM',
        arrivalTime: '5:00 AM',
        fare: 600,
        route: 'Hyderabad - Suryapet - Vijayawada',
      },
    ],
  },
];

export const getAllCities = (): CityData['city'][] => {
  return teluguCitiesData.map((data) => data.city);
};

export const getCityData = (cityId: string): CityData | undefined => {
  return teluguCitiesData.find((data) => data.city.id === cityId);
};

export const getAllPlaces = (): CityData['places'] => {
  return teluguCitiesData.flatMap((data) => data.places);
};

export const getAllUtsavs = (): CityData['utsavs'] => {
  return teluguCitiesData.flatMap((data) => data.utsavs);
};

export const getUpcomingUtsavs = (): CityData['utsavs'] => {
  return getAllUtsavs()
    .filter((utsav) => !utsav.isPast && new Date(utsav.date) >= new Date())
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
};
